server:
  port: 8081
  servlet:
    context-path: /api
  error:
    include-stacktrace: never

spring:
  application:
    name: ms-order
  datasource:
    url: jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: michelflava
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    hibernate:
      ddl-auto: update
  spring:
    kafka:
      producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer

  topic:
    producer-cliente: topic_producer_cliente
    group-id: group_id


springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html
    csrf:
      enabled: false
  show-actuator: true
  default-produces-media-type: "application/json"





  


