server:
  port: '8082'
  servlet:
    context-path: /api

  error:
    include-stacktrace: never

spring:
  application:
    name: ms-history
    main:
      allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_history

springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html
    csrf:
      enabled: false
  show-actuator: true
  default-produces-media-type: "application/json"

