server:
  port: '8082'
  servlet:
    context-path: /api

  error:
    include-stacktrace: never

spring:
  application:
    name: ms-history
    main:
      allow-bean-definition-overriding: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/db_history

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: group_id
      bootstrap-servers: 127.0.0.1:9092
      auto-offset-reset: earliest
topic:
  name:
    consumer: topic.order.history

auto:
  create:
    topics:
      enable: 'true'

springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html
    csrf:
      enabled: false
  show-actuator: true
  default-produces-media-type: "application/json"

